from enum import Enum

class ResponseSignal(Enum):

    FILE_VALID = "FILE_VALID"
    FILE_TYPE_NOT_SUPPORTED = "FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_UPLOAD_FAILURE = "FILE_UPLOAD_FAILURE"